### PR TITLE
fix(parser.py): remove call to deleted method is_family()

### PR DESCRIPTION
**Pull request by joephayes**
I think this will resolve https://github.com/nickreynke/python-gedcom/issues/55

### CODE REVIEW

**Review by nickreynke — APPROVED** [review]

**Comment by nickreynke** [comment]
Seems about right. Was thinking about if `if is_family:` could have been just replaced by a `isinstance(individual, FamilyElement)` but this is also okay for the time being.

Thank you for your contribution! Will close this :)

**Comment by nickreynke** [comment]
Hey @joephayes sorry for the inconvenience. Thought you selected the `master` branch as the main branch so I were able to instantly release a new version but you selected `develop`. The `develop` branch currently has way more commits than the `master` branch so I wouldn't be able to release that yet.

Id you could re-open this pr with the `master` branch selected as the base branch?

Thank you!

**Comment by joephayes** [comment]
No worries! Opened a new PR against `master` - https://github.com/nickreynke/python-gedcom/pull/58

**Comment by nickreynke** [comment]
Thank you! Resolved in #58

**Pull request merged**
