### PR TITLE
Fix for to_gedcom_string()

### PR DESCRIPTION
**Pull request by KeithPetro**
Fix for #27. This should fix an issue where calling to_gedcom_string() for the ROOT element resulted in an empty string. Recursion was also broken and has been fixed.

### CODE REVIEW

**Comment by KeithPetro** [comment]
Looks like the Travis build failed. I'll look into that as soon as I am able to get on my computer again.

**Comment by gburca** [comment]
Any plans to merge this in?

**Comment by KeithPetro** [comment]
Looking over my changes quickly, I think it would've been smarter to just return result instead of returning ''. I think there is an issue with this change, as there is no base return condition if recursive is True. I don't know how I missed that in my original testing.

**Comment by mameen** [comment]
identical fix: https://github.com/mameen/python-gedcom/tree/to_gedcom_string_recursive_fix

**Comment by KeithPetro** [comment]
Hey @nickreynke, any chance of getting this merged in?

@mameen If you're good with it, I can either add you as a contributor to my fork so you can push your tests to this PR, or I could push the tests myself.

**Comment by mameen** [comment]
@KeithPetro you are welcome to cherrypick the fix from my fork.. I lost interest in the project :-D

**Comment by nickreynke** [comment]
@KeithPetro and @mameen: I'm very sorry for the late reply. Due to some private problems, I experienced the last months, I didn't get the time to maintain the project. I'll publish a new version to Pypi later this day. Thank you for contributing!

**Comment by mameen** [comment]
@nickreynke I hope things are good now, and thanks for looking after this project.

**Pull request merged**
